chain: dynamic-lumia-prism-mainnet
datadir: /data
zkevm.l2-chain-id: 994873017
zkevm.l2-datastreamer-url: L2_DATASTREAMER_URL
zkevm.l2-sequencer-rpc-url: L2_SEQUENCER_RPC_URL

zkevm.l1-chain-id: 1
zkevm.l1-rollup-id: 7
zkevm.l1-rpc-url: L1_RPC_URL
zkevm.address-sequencer: 0xCe06F92A73e888a7eb8885Bf4741eF4E5490f8Fb
zkevm.address-zkevm: 0x92726F7dE49300DBdb60930066bc1d0803c0740B
zkevm.address-admin: 0x258862dec9a77db57b398c441390783293E2a7A1
zkevm.address-rollup: 0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2
zkevm.address-ger-manager: 0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb

zkevm.l1-matic-contract-address: 0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6
zkevm.l1-block-range: 400
zkevm.l1-query-delay: 10000
zkevm.l1-first-block: 16896721
zkevm.l1-cache-enabled: false
zkevm.l1-highest-block-type: "finalized"
zkevm.rpc-ratelimit: 50
zkevm.data-stream-host: "0.0.0.0"
zkevm.executor-strict: false
zkevm.executor-urls: ""
zkevm.data-stream-port: 9000
zkevm.datastream-version: 3
zkevm.data-stream-inactivity-timeout: "10m"
zkevm.data-stream-inactivity-check-interval: "5m"
zkevm.data-stream-writeTimeout: "20s"
zkevm.default-gas-price: 1000000000

zkevm.allow-free-transactions: false
zkevm.allow-pre-eip155-transactions: true

zkevm.rpc-get-batch-witness-concurrency-limit: 2

zkevm.witness-full: false

zkevm.disable-virtual-counters: true
zkevm.mock-witness-generation: true

zkevm.initial-batch.config: /dynamic-configs/dynamic-lumia-prism-mainnet-first-batch-config.json


rpc.batch.limit: 1000

http: true
http.api : ["eth","debug","net","trace","web3","erigon","txpool","zkevm"]
http.port: 8545
private.api.addr: "localhost:9093"
http.addr: 0.0.0.0
http.vhosts: "*"
http.corsdomain: "*"
externalcl: true

metrics: true
metrics.addr: "0.0.0.0"
metrics.port: 9090

db.read.concurrency: 20000
log.console.verbosity: "info"
ws: true
