chain: dynamic-lumia-beam-testnet
datadir: /data
zkevm.l2-chain-id: 2030232745
zkevm.l2-datastreamer-url: L2_DATASTREAMER_URL
zkevm.l2-sequencer-rpc-url: L2_SEQUENCER_RPC_URL

zkevm.l1-chain-id: 11155111
zkevm.l1-rollup-id: 35
zkevm.l1-rpc-url: L1_RPC_URL

zkevm.address-sequencer: 0x61030eFaF205a8E4108A1072269cF8334Bc4BD37

zkevm.l1-contract-address-check: false
zkevm.l1-contract-address-retrieve: false
zkevm.address-zkevm: 0x94F74eD7EF1F24F83c7aa8af15ff0E55032cf7Fb
zkevm.address-admin: 0x978d8944A2a6E0e988761B31bFdf8EF873f526f4
zkevm.address-rollup: 0x32d33D5137a7cFFb54c5Bf8371172bcEc5f310ff
zkevm.address-ger-manager: 0xAd1490c248c5d3CbAE399Fd529b79B42984277DF

zkevm.l1-matic-contract-address: 0x6a7c3F4B0651d6DA389AD1d11D962ea458cDCA70
zkevm.l1-block-range: 400
zkevm.l1-query-delay: 10000
zkevm.l1-first-block: 5158574
zkevm.l1-cache-enabled: false
zkevm.l1-highest-block-type: finalized
zkevm.rpc-ratelimit: 50
zkevm.data-stream-host: "0.0.0.0"
zkevm.executor-strict: false

zkevm.data-stream-port: 6900
zkevm.datastream-version: 3
zkevm.data-stream-inactivity-timeout: "10m"
zkevm.data-stream-inactivity-check-interval: "5m"
zkevm.data-stream-writeTimeout: "5m"
zkevm.default-gas-price: 10000000

zkevm.allow-free-transactions: false
zkevm.allow-pre-eip155-transactions: true

zkevm.sequencer-block-seal-time: 3s
zkevm.sequencer-batch-seal-time: 30m

zkevm.rpc-get-batch-witness-concurrency-limit: 2
zkevm.witness-full: false

zkevm.disable-virtual-counters: true
zkevm.mock-witness-generation: true

zkevm.initial-batch.config: /dynamic-configs/dynamic-lumia-beam-testnet-first-batch-config.json
zkevm.honour-chainspec: true

rpc.batch.limit: 1000
rpc.logs.maxrange: 10000000

txpool.purge.every: 1m
txpool.purge.distance: 3h

http: true
http.api: ["eth", "debug", "net", "trace", "web3", "erigon", "txpool", "zkevm"]
http.port: 8545
private.api.addr: "localhost:9093"
http.addr: 0.0.0.0
http.vhosts: "*"
http.corsdomain: "*"
externalcl: true

metrics: true
metrics.addr: "0.0.0.0"
pprof: false

db.read.concurrency: 20000
log.console.verbosity: "info"
ws: true
ws.port: 8546
ws.addr: 0.0.0.0
ws.api: ["eth", "debug", "net", "trace", "web3", "erigon", "txpool", "zkevm"]

txpool.globalslots: 50000
txpool.globalbasefeeslots: 50000
txpool.globalqueue: 100000
txpool.accountslots: 50000

override.normalcyblock: 11866512
override.londonblock: 11866512
override.shanghaitime: 1765191991
override.cancun: 1765191991
override.prague: 1765191991
override.pmtenabledblock: 11866512